import type { Client } from '@/lib/types';

export const clients: Client[] = [
  {
    id: 'dy',
    name: 'Dylan Y.',
    initials: 'DY',
    since: 'Since Sep 2024',
    goal: 'Bulk',
    duration: '7 months',
    status: 'Active',
    payment: 'Paid',
    lastLogin: 'Today',
    msgRead: true,
    healthScore: 92,
    referrals: 4,
    notes: "One of the most consistent clients. Also building his own AI agency — very driven. Responds well to data and numbers. Hip flexor tightness from desk work.",
    nextPaymentDate: '2026-06-01',
  },
  {
    id: 'jm',
    name: 'James M.',
    initials: 'JM',
    since: 'Since Jan 2025',
    goal: 'Fat loss',
    duration: '3 months',
    status: 'Active',
    payment: 'Paid',
    lastLogin: '2 days ago',
    msgRead: true,
    healthScore: 88,
    referrals: 2,
    notes: "Lower back niggle mentioned in week 2 — programming around it. Very motivated, responds well to direct feedback. Works in finance, high stress. Needs to be reminded to sleep.",
    nextPaymentDate: '2026-05-27',
  },
  {
    id: 'cr',
    name: 'Connor R.',
    initials: 'CR',
    since: 'Since Nov 2024',
    goal: 'Muscle build',
    duration: '5 months',
    status: 'Active',
    payment: 'Paid',
    lastLogin: '4 days ago',
    msgRead: true,
    healthScore: 81,
    referrals: 3,
    notes: "Very consistent. Had a bad month in January — personal issues. Loves heavy compounds. Don't switch to isolation-heavy programmes, he finds them demotivating.",
    nextPaymentDate: '2026-06-05',
  },
  {
    id: 'th',
    name: 'Tom H.',
    initials: 'TH',
    since: 'Since Feb 2025',
    goal: 'Body recomp',
    duration: '2 months',
    status: 'Active',
    payment: 'Due',
    lastLogin: '14 days ago',
    msgRead: false,
    healthScore: 24,
    referrals: 1,
    notes: "Going quiet — hasn't logged in for 2 weeks. May be struggling with consistency. Needs a check-in message. Payment due Friday.",
    nextPaymentDate: '2026-05-15',
  },
  {
    id: 'ak',
    name: 'Aaron K.',
    initials: 'AK',
    since: 'Since Mar 2025',
    goal: 'Fat loss',
    duration: '1 month',
    status: 'Paused',
    payment: 'Paid',
    lastLogin: '10 days ago',
    msgRead: false,
    healthScore: 41,
    referrals: 0,
    notes: "Paused due to holiday. Should be back May 1st. Knee issue — avoid anything high impact. Had a good first month before pausing.",
    nextPaymentDate: '2026-06-10',
  },
];
