import type { CommunityEvent } from '@/lib/types';

export const communityEvents: CommunityEvent[] = [
  {
    id: 'ev1',
    title: 'Weekly Group Call',
    description: 'Open call with Sam — bring your questions, wins, and challenges from the week. No agenda, just real talk.',
    type: 'live-call',
    date: '2026-06-01',
    time: '7:00 PM BST',
    duration: '60 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'attending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'attending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'declined', reason: 'Travelling that weekend' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'pending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'attending' },
    ],
  },
  {
    id: 'ev2',
    title: 'Nutrition Q&A',
    description: 'Live Q&A deep dive focused on nutrition strategy. Submit your questions in the WhatsApp group beforehand for priority answers.',
    type: 'q-and-a',
    date: '2026-06-07',
    time: '6:00 PM BST',
    duration: '45 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'attending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'pending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'declined', reason: 'Work shift clash' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'attending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'attending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'pending' },
    ],
  },
  {
    id: 'ev3',
    title: 'Weekly Group Call',
    description: 'Open call with Sam — bring your questions, wins, and challenges from the week. No agenda, just real talk.',
    type: 'live-call',
    date: '2026-06-08',
    time: '7:00 PM BST',
    duration: '60 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'pending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'pending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'pending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'pending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'pending' },
    ],
  },
  {
    id: 'ev4',
    title: 'Training Form Workshop',
    description: "Sam walks through the most common form mistakes he sees across check-ins. Bring questions — this is interactive.",
    type: 'workshop',
    date: '2026-06-14',
    time: '2:00 PM BST',
    duration: '90 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'attending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'attending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'attending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'declined', reason: 'Family commitment' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'attending' },
    ],
  },
  {
    id: 'ev5',
    title: 'Weekly Group Call',
    description: 'Open call with Sam — bring your questions, wins, and challenges from the week. No agenda, just real talk.',
    type: 'live-call',
    date: '2026-06-15',
    time: '7:00 PM BST',
    duration: '60 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'pending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'pending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'pending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'pending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'pending' },
    ],
  },
  {
    id: 'ev6',
    title: '30-Day Challenge Kickoff',
    description: 'The summer accountability challenge starts here. Sam explains the rules, prizes, and how to track progress. Do not miss this.',
    type: 'challenge',
    date: '2026-06-21',
    time: '10:00 AM BST',
    duration: '30 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'attending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'attending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'attending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'attending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'attending' },
    ],
  },
  {
    id: 'ev7',
    title: 'Monthly Wrap-Up Call',
    description: 'End of June recap — wins shared, lessons learned, plan for July. High energy session, expect guest appearances.',
    type: 'social',
    date: '2026-06-29',
    time: '7:00 PM BST',
    duration: '90 min',
    link: 'https://zoom.us/placeholder',
    rsvps: [
      { clientId: 'dylan', clientName: 'Dylan', clientInitials: 'DM', status: 'pending' },
      { clientId: 'c2', clientName: 'Jamie K', clientInitials: 'JK', status: 'pending' },
      { clientId: 'c3', clientName: 'Lee H', clientInitials: 'LH', status: 'pending' },
      { clientId: 'c4', clientName: 'Priya S', clientInitials: 'PS', status: 'pending' },
      { clientId: 'c5', clientName: 'Tom R', clientInitials: 'TR', status: 'pending' },
      { clientId: 'c6', clientName: 'Marcus D', clientInitials: 'MD', status: 'pending' },
    ],
  },
];
