import type { Supplement } from '@/lib/types';

export const supplements: Supplement[] = [
  {
    id: '1',
    icon: '💊',
    name: 'Multivitamin',
    description: '1 per day — building blocks of the body, helps maintain good health.',
    essential: true,
  },
  {
    id: '2',
    icon: '🐟',
    name: 'Omega 3',
    description: '1 per day — binds to receptors in cells that regulate genetic function.',
    essential: true,
  },
  {
    id: '3',
    icon: '☀️',
    name: 'Vitamin D',
    description: '1 per day — bone health and immune support; provides what the sun provides.',
    essential: true,
  },
  {
    id: '4',
    icon: '🍊',
    name: 'Vitamin C',
    description: '1 per day — protects cells, maintains healthy skin, blood vessels, bones and cartilage.',
    essential: true,
  },
  {
    id: '5',
    icon: '🥤',
    name: 'Whey Isolate',
    description: '1–2 scoops per day (diet dependant) — recovery, lean muscle building and fat loss benefits.',
    essential: true,
  },
  {
    id: '6',
    icon: '⚡',
    name: 'Creatine',
    description: '5g per day — increases physical performance in successive bursts of short-term high intensity exercise.',
    essential: true,
  },
  {
    id: '7',
    icon: '🌿',
    name: 'Digest Enzyme',
    description: '1 per day — aids digestion of protein, carbohydrates, fat and fibre.',
    essential: false,
  },
  {
    id: '8',
    icon: '🫀',
    name: 'Cod Liver Oil',
    description: '1 per day — ideal supplement for both heart health and joints.',
    essential: false,
  },
  {
    id: '9',
    icon: '💧',
    name: 'Electrolytes',
    description: '1g per day — regulate pH levels and muscles, keep you hydrated.',
    essential: false,
  },
  {
    id: '10',
    icon: '🦐',
    name: 'Krill Oil',
    description: '1 per day — improves general health, post-exercise immune function, muscular strength and athletic performance.',
    essential: false,
  },
  {
    id: '11',
    icon: '🔋',
    name: 'COQ10',
    description: '1 per day — helps with muscle growth and muscle strength.',
    essential: false,
  },
  {
    id: '12',
    icon: '💪',
    name: "EAA's",
    description: '15g per day intra-workout — 9 essential amino acids for energy, muscle building, strength and boosted metabolism.',
    essential: false,
  },
];
