import type { Webinar } from '@/lib/types';

export const upcomingWebinars: Webinar[] = [];

export const recordedWebinars: Webinar[] = [
  {
    id: 'w16',
    month: '', day: '',
    title: 'Webinar — Sleep',
    meta: 'Loom · Full recording',
    tag: 'Recovery',
    recorded: true,
    url: 'https://www.loom.com/share/16d04298772d4d53bfc1d7aa7ae9e396',
  },
  {
    id: 'w19',
    month: '', day: '',
    title: 'Stress',
    meta: 'Loom · Full recording',
    tag: 'Mindset',
    recorded: true,
    url: 'https://www.loom.com/share/182cf3eb4289403e92d6283fe19da5a6',
  },
  {
    id: 'w20',
    month: '', day: '',
    title: 'Motivation',
    meta: 'Loom · Full recording',
    tag: 'Mindset',
    recorded: true,
    url: 'https://www.loom.com/share/fd901d83c07947378c17bb8fd04d7d0b',
  },
  {
    id: 'w21',
    month: '', day: '',
    title: 'Training',
    meta: 'Loom · Full recording',
    tag: 'Training',
    recorded: true,
    url: 'https://www.loom.com/share/4be1d3f2d4e94862a6b9e46e9b685867',
  },
  {
    id: 'w22',
    month: '', day: '',
    title: 'Fat Loss Fundamentals',
    meta: 'Loom · Full recording',
    tag: 'Nutrition',
    recorded: true,
    url: 'https://www.loom.com/share/52b2881240864c3f9d191df4ab19b247',
  },
  {
    id: 'w23',
    month: '', day: '',
    title: 'Recovery & Fatigue',
    meta: 'Loom · Full recording',
    tag: 'Recovery',
    recorded: true,
    url: 'https://www.loom.com/share/0006b1cda48d457da5eab7b5e530c95e',
  },
  {
    id: 'w25',
    month: '', day: '',
    title: 'Client Adherence',
    meta: 'Loom · Full recording',
    tag: 'Mindset',
    recorded: true,
    url: 'https://www.loom.com/share/6e3749e1eab24440b2858ed4ddc168b9',
  },
  {
    id: 'w28',
    month: '', day: '',
    title: 'Webinar — Perfecting Routine',
    meta: 'Loom · Full recording',
    tag: 'Lifestyle',
    recorded: true,
    url: 'https://www.loom.com/share/38b553c8026745bb88981f6adcbe141b',
  },
  {
    id: 'w37',
    month: '', day: '',
    title: 'Managing Socials & Weekends',
    meta: 'Loom · Full recording',
    tag: 'Lifestyle',
    recorded: true,
    url: 'https://www.loom.com/share/0aaac01f431441968b4c213cc0a006dc',
  },
];
